version: "3"
services:
  mysql:
    container_name: api_mysql
    build:
      context: ./
      dockerfile: mysql/Dockerfile.dev
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: nodeAPI
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      TZ: Asia/Tokyo
    ports:
      - 4306:3306
    networks:
      - default

  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    volumes:
      - ./api/openapi.yaml:/openapi.yaml
    ports:
      - 80:8080
    environment:
      SWAGGER_JSON: ./api/openapi.yaml

  # swagger:
  #   image: swaggerapi/swagger-editor
  #   container_name: swagger
  #   ports:
  #     - 80:8080

  # api:
  #   container_name: node_api
  #   build:
  #     context: ./
  #     dockerfile: api/Dockerfile.dev
  #   volumes:
  #     - ./api:/code
  #     - /api/node_modules # マウントで消さないため
  #   ports:
  #     - 8000:8000
  #   working_dir: /api
  #   command: yarn dev
  #   depends_on:
  #     - mysql
  #   networks:
  #     - default

networks:
  default:
    external: false
volumes:
  mysql-data:
